temp: remove format check

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -183,14 +183,14 @@ runs:
           exit 1
         fi
 
-    - name: Terraform Format Status
-      shell: bash
-      run: |
-        if [[ '${{ inputs.require-formatting }}' == 'true' ]] && [[ '${{ steps.fmt.outputs.fmt-outcome }}' == 'failure' ]]; then
-          echo ${{ steps.fmt.outputs.stdout }}
-          echo ${{ steps.fmt.outputs.stderr }}
-          exit 1
-        fi
+#     - name: Terraform Format Status
+#       shell: bash
+#       run: |
+#         if [[ '${{ inputs.require-formatting }}' == 'true' ]] && [[ '${{ steps.fmt.outputs.fmt-outcome }}' == 'failure' ]]; then
+#           echo ${{ steps.fmt.outputs.stdout }}
+#           echo ${{ steps.fmt.outputs.stderr }}
+#           exit 1
+#         fi
 
     - name: Terraform Apply
       shell: bash
